services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ring-us-server
    env_file:
      - ${ENV_FILE}
    depends_on:
      - database
      - redis
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    restart: always

  database:
    image: mysql:8.4.4
    container_name: ring-us-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      --port=${DB_PORT} --max_allowed_packet=32M
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: no
    volumes:
      - ring-us-database:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: ring-us-redis
    environment:
      REDIS_PASSWORD : ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    volumes:
      - ring-us-redis:/var/lib/redis
volumes:
  ring-us-database:
  ring-us-redis:
