server:
  port: ${SPRING_PORT}
  servlet:
    context-path: ${BASE_PATH}
    session:
      cookie:
        same-site : none
        secure: false
  error:
    include-stacktrace: never

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      auth: true
      starttls:
        enable: true

university:
  file:
    path: ${UNIVERSITY_FILE_PATH}

verification:
  max_failed_attempts: ${MAX_FAILED_ATTEMPTS}
  default_expiry: ${DEFAULT_EXPIRY}
