ALTER TABLE mentor
    MODIFY job_category ENUM(
    'DATA','DESIGN','DEVELOPMENT',
    'FINANCE','FINANCE_CONSULTING_VC',
    'GRADUATE_SCHOOL','HR_SUPPORT','LEGAL',
    'MARKETING','MEDICAL','SALES_CUSTOMER','SERVICE_PLANNING'
    );

ALTER TABLE mentor
    MODIFY detailed_job ENUM(
    'ACCOUNTING_FINANCE','AE','ANALYST','ART_DIRECTOR',
    'B2B_SALES','B2C_SALES','BACKEND','BIO_RESEARCHER','BI_ENGINEER',
    'BRAND_DESIGN','BRAND_MARKETING','BROADCAST_PD','BUSINESS_DEVELOPMENT',
    'CLINICAL_DOCTOR','CLINICAL_RESEARCHER','CLOUD','COMPLIANCE','CONSULTANT',
    'CONTENT_MARKETING','COPYWRITER','CREATIVE_DIRECTING','CSM_CX','CX_MANAGER',
    'DATA_ANALYST','DATA_ARCHITECT','DATA_ENGINEER','DATA_SCIENTIST','DEVOPS',
    'DIGITAL_SOCIAL_MARKETING','DOMESTIC_GRADUATE_SCHOOL','FRONTEND','FULLSTACK',
    'GENERAL_AFFAIRS','GRAPHIC_DESIGN','GROWTH_MARKETING','HR_OPERATION',
    'HR_PLANNING','IB_PE_ALTERNATIVE_INVESTMENT','IOS_ANDROID','KAM','LABOR',
    'LAWYER','LAW_FIRM_STAFF','LEGAL_ADVISOR','LEGAL_COUNSEL',
    'MACHINE_LEARNING_ENGINEER','MEDIA_PLANNER','MEDICAL_DEVICE_RND',
    'OPERATION_PLANNING','ORGANIZATION_CULTURE',
    'OTHER_DATA','OTHER_DESIGN','OTHER_DEVELOPMENT',
    'OTHER_FINANCE','OTHER_FINANCE_CONSULTING_VC',
    'OTHER_GRADUATE_SCHOOL','OTHER_HR_SUPPORT','OTHER_LEGAL','OTHER_MARKETING',
    'OTHER_MEDICAL','OTHER_SALES_CUSTOMER','OTHER_SERVICE_PLANNING',
    'OVERSEAS_GRADUATE_SCHOOL','OVERSEAS_SALES','PATENT','PATENT_ENGINEER',
    'PERFORMANCE_MARKETING','PHARMACEUTICAL_RESEARCHER','PM_PO','PR',
    'PRODUCT_DESIGN','RECRUITER','RECRUITMENT','RESEARCH_ANALYST',
    'SALES_SUPPORT','SECURITY','SERVICE_PLANNING','SOLUTION_CONSULTANT',
    'STARTUP','STRATEGY_PLANNING','SYSTEM_NETWORK','TALENT_DEVELOPMENT',
    'TECHNICAL_SALES','UX_UI_DESIGN','VC_INVESTMENT','WEB_DESIGN'
    );