name: CI Workflow

on:
  pull_request:
    branches:
      - main         # main 브랜치로의 PR
      - develop      # develop 브랜치로의 PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. JDK 23 설정
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'

      # 3. Gradle 캐시 적용
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create .env.dev file
        run: |
          touch .env.dev
          echo "${{ secrets.ENV }}" >> .env.dev

      # 4. dev.sh 실행 (환경 변수 로드 및 빌드 준비)
      - name: Run dev.sh
        run: |
          chmod +x ./dev.sh    # dev.sh에 실행 권한 부여
          ./dev.sh             # dev.sh 실행
